-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 13:37:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cinema` DEFAULT CHARACTER SET utf8 ;
USE `Cinema` ;

-- -----------------------------------------------------
-- Table `Cinema`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`movie` (
  `id_movie` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `year` DATE NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `age_rating` INT NOT NULL,
  `runtime_min` INT NOT NULL,
  `director` VARCHAR(45) NOT NULL,
  `script` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_movie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`genre` (
  `id_genre` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`showtime_format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`showtime_format` (
  `id_showtime_format` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_showtime_format`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`hall_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`hall_type` (
  `id_hall_type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id_hall_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`hall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`hall` (
  `id_hall` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `total_seats` INT NOT NULL,
  `total_rows` INT NOT NULL,
  `in/out` VARCHAR(3) NOT NULL,
  `capacity` INT NOT NULL,
  `halltype_id` INT NOT NULL,
  PRIMARY KEY (`id_hall`),
  INDEX `halltype_idx` (`halltype_id` ASC) VISIBLE,
  CONSTRAINT `halltype`
    FOREIGN KEY (`halltype_id`)
    REFERENCES `Cinema`.`hall_type` (`id_hall_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`showtime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`showtime` (
  `id_showtime` INT NOT NULL,
  `movie_id_st` INT NOT NULL,
  `show_time` DATETIME NOT NULL,
  `showtimeformat_id` INT NOT NULL,
  `hall_id_st` INT NOT NULL,
  PRIMARY KEY (`id_showtime`, `movie_id_st`),
  INDEX `movie_idx` (`movie_id_st` ASC) VISIBLE,
  INDEX `showtime_fornat_idx` (`showtimeformat_id` ASC) VISIBLE,
  INDEX `hall_idx` (`hall_id_st` ASC) VISIBLE,
  CONSTRAINT `movie_st`
    FOREIGN KEY (`movie_id_st`)
    REFERENCES `Cinema`.`movie` (`id_movie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `showtime_fornat`
    FOREIGN KEY (`showtimeformat_id`)
    REFERENCES `Cinema`.`showtime_format` (`id_showtime_format`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hall_st`
    FOREIGN KEY (`hall_id_st`)
    REFERENCES `Cinema`.`hall` (`id_hall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`decoration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`decoration` (
  `id_decoration` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`id_decoration`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`client` (
  `id_client` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `bonuses` INT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`bill` (
  `id_bill` INT NOT NULL,
  `booking_fee` INT NOT NULL,
  `date` DATE NOT NULL,
  `client_id_b` INT NOT NULL,
  PRIMARY KEY (`id_bill`),
  INDEX `client_idx` (`client_id_b` ASC) VISIBLE,
  CONSTRAINT `client_b`
    FOREIGN KEY (`client_id_b`)
    REFERENCES `Cinema`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`equipment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`equipment_type` (
  `id_equipment_type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_equipment_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`equipment` (
  `id_equipment` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `equipment_type_id` INT NOT NULL,
  PRIMARY KEY (`id_equipment`),
  INDEX `fk_equipment_equipment_type1_idx` (`equipment_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipment_equipment_type1`
    FOREIGN KEY (`equipment_type_id`)
    REFERENCES `Cinema`.`equipment_type` (`id_equipment_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`booking_hall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`booking_hall` (
  `id_booking_hall` INT NOT NULL,
  `booking_fee` INT NOT NULL,
  `when` DATE NOT NULL,
  `time` TIME NOT NULL,
  `decription` VARCHAR(45) NULL,
  `hall_id_bh` INT NOT NULL,
  `decoration_id` INT NOT NULL,
  `movie_id_bh` INT NOT NULL,
  `client_id_bh` INT NOT NULL,
  `bill_id_bh` INT NOT NULL,
  `equipment_id` INT NULL,
  PRIMARY KEY (`id_booking_hall`),
  INDEX `hall_idx` (`hall_id_bh` ASC) VISIBLE,
  INDEX `decoration_idx` (`decoration_id` ASC) VISIBLE,
  INDEX `movie_idx` (`movie_id_bh` ASC) VISIBLE,
  INDEX `client_idx` (`client_id_bh` ASC) VISIBLE,
  INDEX `bill_idx` (`bill_id_bh` ASC) VISIBLE,
  INDEX `fk_booking_hall_equipment1_idx` (`equipment_id` ASC) VISIBLE,
  CONSTRAINT `hall_bt`
    FOREIGN KEY (`hall_id_bh`)
    REFERENCES `Cinema`.`hall` (`id_hall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `decoration_bh`
    FOREIGN KEY (`decoration_id`)
    REFERENCES `Cinema`.`decoration` (`id_decoration`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `movie_bh`
    FOREIGN KEY (`movie_id_bh`)
    REFERENCES `Cinema`.`movie` (`id_movie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `client_bh`
    FOREIGN KEY (`client_id_bh`)
    REFERENCES `Cinema`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bill_bh`
    FOREIGN KEY (`bill_id_bh`)
    REFERENCES `Cinema`.`bill` (`id_bill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_hall_equipment1`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `Cinema`.`equipment` (`id_equipment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`typeforseat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`typeforseat` (
  `id_typeforseat` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_typeforseat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`seat_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`seat_type` (
  `id_seat_type` INT NOT NULL,
  `total_rows` INT NOT NULL,
  `total_seats` INT NOT NULL,
  `typeforseat_id` INT NOT NULL,
  `hall_id_seat_type` INT NOT NULL,
  PRIMARY KEY (`id_seat_type`, `hall_id_seat_type`),
  INDEX `typeforseat_idx` (`typeforseat_id` ASC) VISIBLE,
  INDEX `hall_idx` (`hall_id_seat_type` ASC) VISIBLE,
  CONSTRAINT `typeforseat`
    FOREIGN KEY (`typeforseat_id`)
    REFERENCES `Cinema`.`typeforseat` (`id_typeforseat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hall_id_seat_type`
    FOREIGN KEY (`hall_id_seat_type`)
    REFERENCES `Cinema`.`hall` (`id_hall`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`seat_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`seat_price` (
  `id_seat_price` INT NOT NULL,
  `price` INT NOT NULL,
  `seat_type_id_seat_type` INT NOT NULL,
  `seat_type_hall_id` INT NOT NULL,
  `showtime_id_showtime` INT NOT NULL,
  `showtime_movie_id` INT NOT NULL,
  PRIMARY KEY (`id_seat_price`, `seat_type_id_seat_type`, `seat_type_hall_id`, `showtime_id_showtime`, `showtime_movie_id`),
  INDEX `fk_seat_price_seat_type1_idx` (`seat_type_id_seat_type` ASC, `seat_type_hall_id` ASC) VISIBLE,
  INDEX `fk_seat_price_showtime1_idx` (`showtime_id_showtime` ASC, `showtime_movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_price_seat_type1`
    FOREIGN KEY (`seat_type_id_seat_type` , `seat_type_hall_id`)
    REFERENCES `Cinema`.`seat_type` (`id_seat_type` , `hall_id_seat_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seat_price_showtime1`
    FOREIGN KEY (`showtime_id_showtime` , `showtime_movie_id`)
    REFERENCES `Cinema`.`showtime` (`id_showtime` , `movie_id_st`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`ticket` (
  `id_ticket` INT NOT NULL,
  `seat_number` INT NOT NULL,
  `row_number` INT NOT NULL,
  `bill_id_t` INT NOT NULL,
  `seat_price_id_seat_price` INT NOT NULL,
  `seat_price_seat_type_id_seat_type` INT NOT NULL,
  `seat_price_seat_type_hall_id` INT NOT NULL,
  `seat_price_showtime_id_showtime` INT NOT NULL,
  `seat_price_showtime_movie_id` INT NOT NULL,
  PRIMARY KEY (`id_ticket`, `bill_id_t`, `seat_price_id_seat_price`, `seat_price_seat_type_id_seat_type`, `seat_price_seat_type_hall_id`, `seat_price_showtime_id_showtime`, `seat_price_showtime_movie_id`),
  INDEX `bill_idx` (`bill_id_t` ASC) VISIBLE,
  INDEX `fk_ticket_seat_price1_idx` (`seat_price_id_seat_price` ASC, `seat_price_seat_type_id_seat_type` ASC, `seat_price_seat_type_hall_id` ASC, `seat_price_showtime_id_showtime` ASC, `seat_price_showtime_movie_id` ASC) VISIBLE,
  CONSTRAINT `bill_t`
    FOREIGN KEY (`bill_id_t`)
    REFERENCES `Cinema`.`bill` (`id_bill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_seat_price1`
    FOREIGN KEY (`seat_price_id_seat_price` , `seat_price_seat_type_id_seat_type` , `seat_price_seat_type_hall_id` , `seat_price_showtime_id_showtime` , `seat_price_showtime_movie_id`)
    REFERENCES `Cinema`.`seat_price` (`id_seat_price` , `seat_type_id_seat_type` , `seat_type_hall_id` , `showtime_id_showtime` , `showtime_movie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`club` (
  `id_club` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `decription` VARCHAR(45) NULL,
  `imgURL` VARCHAR(45) NULL,
  `owner_id` INT NOT NULL,
  PRIMARY KEY (`id_club`),
  INDEX `owner_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `owner`
    FOREIGN KEY (`owner_id`)
    REFERENCES `Cinema`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`client_club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`client_club` (
  `client_id_cc` INT NOT NULL,
  `club_id_cc` INT NOT NULL,
  PRIMARY KEY (`client_id_cc`, `club_id_cc`),
  INDEX `club_idx` (`club_id_cc` ASC) VISIBLE,
  CONSTRAINT `client_cc`
    FOREIGN KEY (`client_id_cc`)
    REFERENCES `Cinema`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `club_cc`
    FOREIGN KEY (`club_id_cc`)
    REFERENCES `Cinema`.`club` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`employeetype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`employeetype` (
  `id_employeetype` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_employeetype`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`employee` (
  `id_employee` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  `date_of_employment` DATE NOT NULL,
  `release_date` DATE NULL,
  `epmloyeetype_id` INT NOT NULL,
  PRIMARY KEY (`id_employee`),
  INDEX `type_idx` (`epmloyeetype_id` ASC) VISIBLE,
  CONSTRAINT `type`
    FOREIGN KEY (`epmloyeetype_id`)
    REFERENCES `Cinema`.`employeetype` (`id_employeetype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`employeelogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`employeelogin` (
  `employee_id_employee` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employee_id_employee`),
  CONSTRAINT `fk_employeelogin_employee1`
    FOREIGN KEY (`employee_id_employee`)
    REFERENCES `Cinema`.`employee` (`id_employee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`snack_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`snack_type` (
  `id_snack_type` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_snack_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`snack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`snack` (
  `id_snack` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `snack_type_id` INT NOT NULL,
  PRIMARY KEY (`id_snack`),
  INDEX `snack_type_idx` (`snack_type_id` ASC) VISIBLE,
  CONSTRAINT `snack_type`
    FOREIGN KEY (`snack_type_id`)
    REFERENCES `Cinema`.`snack_type` (`id_snack_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`booking_snack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`booking_snack` (
  `id_booking_snack` INT NOT NULL,
  `snack_qty` INT NOT NULL,
  `booking_fee` INT NOT NULL,
  `snack_id_bs` INT NOT NULL,
  `bill_id_bs` INT NOT NULL,
  PRIMARY KEY (`id_booking_snack`, `snack_id_bs`, `bill_id_bs`),
  INDEX `snack_idx` (`snack_id_bs` ASC) VISIBLE,
  INDEX `bill_idx` (`bill_id_bs` ASC) VISIBLE,
  CONSTRAINT `snack_bs`
    FOREIGN KEY (`snack_id_bs`)
    REFERENCES `Cinema`.`snack` (`id_snack`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bill_bs`
    FOREIGN KEY (`bill_id_bs`)
    REFERENCES `Cinema`.`bill` (`id_bill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`movie_has_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`movie_has_genre` (
  `movie_id_movie` INT NOT NULL,
  `genre_id_genre` INT NOT NULL,
  PRIMARY KEY (`movie_id_movie`, `genre_id_genre`),
  INDEX `fk_movie_has_genre_genre1_idx` (`genre_id_genre` ASC) VISIBLE,
  INDEX `fk_movie_has_genre_movie1_idx` (`movie_id_movie` ASC) VISIBLE,
  CONSTRAINT `fk_movie_has_genre_movie1`
    FOREIGN KEY (`movie_id_movie`)
    REFERENCES `Cinema`.`movie` (`id_movie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_has_genre_genre1`
    FOREIGN KEY (`genre_id_genre`)
    REFERENCES `Cinema`.`genre` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`post` (
  `id_post` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `inf` VARCHAR(45) NOT NULL,
  `client_club_client_id` INT NOT NULL,
  `client_club_club_id` INT NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_post_client_club1_idx` (`client_club_client_id` ASC, `client_club_club_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_client_club1`
    FOREIGN KEY (`client_club_client_id` , `client_club_club_id`)
    REFERENCES `Cinema`.`client_club` (`client_id_cc` , `club_id_cc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`favorite_movies_of_club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`favorite_movies_of_club` (
  `club_id_club` INT NOT NULL,
  `movie_id_movie` INT NOT NULL,
  PRIMARY KEY (`club_id_club`, `movie_id_movie`),
  INDEX `fk_club_has_movie_movie1_idx` (`movie_id_movie` ASC) VISIBLE,
  INDEX `fk_club_has_movie_club1_idx` (`club_id_club` ASC) VISIBLE,
  CONSTRAINT `fk_club_has_movie_club1`
    FOREIGN KEY (`club_id_club`)
    REFERENCES `Cinema`.`club` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_club_has_movie_movie1`
    FOREIGN KEY (`movie_id_movie`)
    REFERENCES `Cinema`.`movie` (`id_movie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`favorite_genres_of_club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`favorite_genres_of_club` (
  `genre_id_genre` INT NOT NULL,
  `club_id_club` INT NOT NULL,
  PRIMARY KEY (`genre_id_genre`, `club_id_club`),
  INDEX `fk_genre_has_club_club1_idx` (`club_id_club` ASC) VISIBLE,
  INDEX `fk_genre_has_club_genre1_idx` (`genre_id_genre` ASC) VISIBLE,
  CONSTRAINT `fk_genre_has_club_genre1`
    FOREIGN KEY (`genre_id_genre`)
    REFERENCES `Cinema`.`genre` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_genre_has_club_club1`
    FOREIGN KEY (`club_id_club`)
    REFERENCES `Cinema`.`club` (`id_club`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`favorite_movies_of_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`favorite_movies_of_client` (
  `client_id_client` INT NOT NULL,
  `movie_id_movie` INT NOT NULL,
  PRIMARY KEY (`client_id_client`, `movie_id_movie`),
  INDEX `fk_client_has_movie_movie1_idx` (`movie_id_movie` ASC) VISIBLE,
  INDEX `fk_client_has_movie_client1_idx` (`client_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_movie_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `Cinema`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_movie_movie1`
    FOREIGN KEY (`movie_id_movie`)
    REFERENCES `Cinema`.`movie` (`id_movie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`favorite_genres_of_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`favorite_genres_of_client` (
  `client_id_client` INT NOT NULL,
  `genre_id_genre` INT NOT NULL,
  PRIMARY KEY (`client_id_client`, `genre_id_genre`),
  INDEX `fk_client_has_genre_genre1_idx` (`genre_id_genre` ASC) VISIBLE,
  INDEX `fk_client_has_genre_client1_idx` (`client_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_client_has_genre_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `Cinema`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_has_genre_genre1`
    FOREIGN KEY (`genre_id_genre`)
    REFERENCES `Cinema`.`genre` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cinema`.`promo-code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cinema`.`promo-code` (
  `id_promo-code` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `minus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_promo-code`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
